---
name: on_hello_event1
pack: practice
description: Sample rule firing on practice.event1.
enabled: true
trigger:
    type: practice.event1
action:
    ref: practice.greet
    parameters:
        greeting: Yo